apiVersion: 1

deleteDatasources:
  - name: ${GRAFANA_DATASOURCE_INFLUXDB_NAME}
    orgId: 1

datasources:
  - name: ${GRAFANA_DATASOURCE_INFLUXDB_NAME}
    type: influxdb
    access: proxy
    url: http://${INFLUXDB_HOST}:${INFLUXDB_PORT}
    isDefault: true
    jsonData:
      version: Flux
      organization: ${DOCKER_INFLUXDB_INIT_ORG}
      defaultBucket: ${DOCKER_INFLUXDB_INIT_BUCKET}
      httpMode: POST
    secureJsonData:
      token: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    editable: true
    version: 1
