services:
  telegraf:
    image: telegraf:alpine
    container_name: host.telegraf
    restart: unless-stopped
    hostname: telegraf
    env_file:
      - .env
    volumes:
      - /:/hostfs:ro
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - skynet

  prometheus:
    image: prom/prometheus:latest
    container_name: host.prometheus
    restart: unless-stopped
    hostname: prometheus
    depends_on:
      - telegraf
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    networks:
      - skynet

  influxdb:
    image: influxdb:alpine
    container_name: host.influxdb
    restart: unless-stopped
    hostname: influxdb
    depends_on:
      - telegraf
    env_file:
      - .env
    volumes:
      - influxdb-data:/var/lib/influxdb2
    ports:
      - ${INFLUXDB_PORT}:8086
    networks:
      - skynet

  grafana:
    image: grafana/grafana-oss:latest
    container_name: host.grafana
    restart: unless-stopped
    hostname: grafana
    depends_on:
      - influxdb
      - telegraf
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/startup.sh:/startup.sh:ro
    ports:
      - 3000:3000
    networks:
      - skynet
    command: ["/bin/sh", "/startup.sh"]

volumes:
  influxdb-data:
  grafana-data:
  prometheus-data:

networks:
  skynet:
    driver: bridge
