services:
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./homarr/appdata:/appdata
      - ./certs/homarr/homarr.crt:/appdata/trusted-certificates/homarr.crt:ro
      - ./certs/homarr/homarr.key:/appdata/trusted-certificates/homarr.key:ro
    env_file:
      - .env
    ports:
      - 7575:7575