apiVersion: 1

groups:
  - orgId: 1
    name: System-Health-Monitoring
    folder: System
    interval: 5m
    rules:
      - uid: aedcrgl42sp34c
        title: CPU Temperature
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: aedcqlgeqb85ce
            model:
              datasource:
                type: influxdb
                uid: aedcqlgeqb85ce
              instant: false
              intervalMs: 1000
              maxDataPoints: 43200
              query: "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"telegraf\")\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"temp\" and\r\n    r[\"_field\"] == \"temp\" and\r\n    r[\"sensor\"] == \"cpu_thermal\" \r\n  )\r\n  "
              range: true
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - B
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              refId: B
              type: reduce
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 65
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        dashboardUid: edg269tnjme4gd
        panelId: 9
        noDataState: NoData
        execErrState: Error
        for: 5m
        annotations:
          __dashboardUid__: edg269tnjme4gd
          __panelId__: "9"
        isPaused: false
      - uid: dedcsf88y9k3kc
        title: Memory Used Percent
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: aedcqlgeqb85ce
            model:
              datasource:
                type: influxdb
                uid: aedcqlgeqb85ce
              instant: false
              intervalMs: 1000
              maxDataPoints: 43200
              query: "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"telegraf\")\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"mem\" and\r\n    r[\"_field\"] == \"used_percent\"\r\n  )"
              range: true
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - B
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              refId: B
              type: reduce
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 75
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        dashboardUid: edg269tnjme4gd
        panelId: 1
        noDataState: NoData
        execErrState: Error
        for: 5m
        annotations:
          __dashboardUid__: edg269tnjme4gd
          __panelId__: "1"
        isPaused: false
      - uid: eedcstotsyl8ga
        title: Disk Used Percent
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: aedcqlgeqb85ce
            model:
              datasource:
                type: influxdb
                uid: aedcqlgeqb85ce
              instant: false
              intervalMs: 1000
              maxDataPoints: 43200
              query: "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"telegraf\")\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"disk\" and\r\n    r[\"_field\"] == \"used_percent\" and\r\n    r[\"device\"] == \"mmcblk0p2\"\r\n  )"
              range: true
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - B
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              refId: B
              type: reduce
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 80
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        dashboardUid: edg269tnjme4gd
        panelId: 4
        noDataState: NoData
        execErrState: Error
        for: 5m
        annotations:
          __dashboardUid__: edg269tnjme4gd
          __panelId__: "4"
        isPaused: false
