apiVersion: 1

deleteDatasources:
  - name: InfluxDB
    orgId: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: home
      defaultBucket: telegraf
      httpMode: POST
    secureJsonData:
      token: 
    editable: true
    version: 1
