{
 "title": "System",
 "tags": [
  "cpu",
  "memory",
  "temperature"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "BUCKET", "label": "Bucket", "query": "${VAR_BUCKET}" },
   { "name": "HOST", "label": "Hostname", "query": "${VAR_HOST}" },
   {
    "name": "CPU_NAME",
    "label": "CPU",
    "query": "from(bucket: \"${BUCKET}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"${HOST}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> distinct(column: \"cpu\")\r\n"
   },
   {
    "name": "CPU_FIELD",
    "label": "CPU Fields",
    "query": "from(bucket: \"${BUCKET}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"${HOST}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\" and r[\"_field\"] != \"usage_idle\")\r\n  |> distinct(column: \"_field\")\r\n"
   },
   {
    "name": "DISK_DEVICE",
    "label": "Disk device",
    "query": "from(bucket: \"${BUCKET}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"${HOST}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\r\n  |> distinct(column: \"device\")\r\n"
   }
  ]
 },
 "panels": [
  { "title": "Quick Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${BUCKET}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"${HOST}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${BUCKET}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"${HOST}\")\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"temp\" and\r\n    r[\"_field\"] == \"temp\" and\r\n    r[\"sensor\"] == \"cpu_thermal\" \r\n  )\r\n  "
    }
   ]
  },
  {
   "title": "Memory Used Percent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${BUCKET}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"${HOST}\")\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"mem\" and\r\n    r[\"_field\"] == \"used_percent\"\r\n  )"
    }
   ]
  },
  {
   "title": "Memory Available Percent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${BUCKET}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"${HOST}\")\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"mem\" and\r\n    r[\"_field\"] == \"available_percent\"\r\n  )"
    }
   ]
  },
  {
   "title": "Disk Used Percent ($DISK_DEVICE)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${BUCKET}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"${HOST}\")\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"disk\" and\r\n    r[\"_field\"] == \"used_percent\" and\r\n    r[\"device\"] == \"${DISK_DEVICE}\"\r\n  )\r\n  |> group(columns: [\"device\"])"
    }
   ]
  },
  {
   "title": "Disk Free ($DISK_DEVICE)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${BUCKET}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"${HOST}\")\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"disk\" and\r\n    r[\"_field\"] == \"free\" and\r\n    r[\"device\"] == \"${DISK_DEVICE}\"\r\n  )\r\n  |> group(columns: [\"device\"])"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"${BUCKET}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"${HOST}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> derivative(unit: 1s, nonNegative: false, columns: [\"_value\"], timeColumn: \"_time\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"derivative\")\r\n"
    }
   ]
  },
  { "title": "CPU $CPU_NAME", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "CPU_NAME" },
  {
   "title": "CPU $CPU_NAME $CPU_FIELD",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "repeat": "CPU_FIELD",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${BUCKET}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"${HOST}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${CPU_FIELD}\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"${CPU_NAME}\")\r\n  "
    }
   ]
  }
 ]
}